# Generated by Django 6.1.1 on 2026-09-28 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='denumire')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ferestre', 'Ferestre'), ('usi', 'Uși'), ('constructii', 'Construcții din aluminiu și PVC')], max_length=20, verbose_name='categorie')),
                ('material', models.CharField(choices=[('pvc', 'PVC'), ('aluminiu', 'Aluminiu'), ('pvc-aluminiu', 'PVC și aluminiu')], max_length=20, verbose_name='material')),
                ('icon', models.CharField(choices=[('window', 'Fereastră'), ('door', 'Ușă'), ('facade', 'Fațadă'), ('veranda', 'Verandă'), ('sliding', 'Glisant'), ('balcony', 'Balcon')], default='window', help_text='Afișată când produsul nu are imagine.', max_length=20, verbose_name='pictogramă')),
                ('short_description', models.CharField(max_length=255, verbose_name='descriere scurtă')),
                ('description', models.TextField(help_text='Paragrafele se separă printr-un rând liber.', verbose_name='descriere')),
                ('features', models.TextField(blank=True, help_text='O caracteristică pe fiecare rând.', verbose_name='caracteristici')),
                ('image', models.FileField(blank=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagine')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordine')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicat')),
            ],
            options={
                'verbose_name': 'produs',
                'verbose_name_plural': 'produse',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nume')),
                ('phone', models.CharField(max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='primit la')),
                ('is_handled', models.BooleanField(default=False, verbose_name='rezolvat')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='br_main.product', verbose_name='produs de interes')),
            ],
            options={
                'verbose_name': 'cerere de contact',
                'verbose_name_plural': 'cereri de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
